name: "Update git"
description: "Update Git to >= 2.18 so that CI actually gives us a .git directory that we need for the githash"
runs:
  using: "composite"
  steps:
    - run: |
        sudo add-apt-repository ppa:git-core/ppa --yes --update
        sudo apt-get install -y git
      shell: bash
